### ISSUE TITLE
Where is `rookPositions()` defined?

### ISSUE THREAD

**Issue by micycle1** [Atrix256/SampleZoo#7]
I was porting some of the LDS distributions to use them in a Java project. The `NRooks()` method references a `rookPositions()` method however it doesn't seem to be included in the source code?

**Comment by Atrix256** [comment]
Hey there!
Is this the code you are talking about?
https://github.com/Atrix256/SampleZoo/blob/master/src/families/_2d/samples/lds/LDS.cpp#L111

rookPositions is the std::vector<size_t> defined at the top of the function, and is made by making an array with values 0, 1, 2, ... numValues and then shuffling them.

**Comment by micycle1** [comment]
Yes, that was the code.

Oh right, it's a vector initialisation🤦.

**Comment by Atrix256** [comment]
ha, no problem. I apologize for this being vapor ware. If someone followed through on this kind of thing, it could be quite useful.
Real cool you are porting some to a java project. What does your program do?

**Comment by micycle1** [comment]
I'll be adding a point distribution class to [this](https://github.com/micycle1/PGS) geometry project. The idea is point sets (having different characteristics) can serve as input into other methods -- delaunay triangulation and the like.
